namespace ChromaListe.Web.Core;

public enum Ball
{
    Poke = 0,
    Great = 1,
    Ultra = 2,
    Master = 3,
    Net = 4,
    Dive = 5,
    Nest = 6,
    Repeat = 7,
    Timer = 8,
    Luxury = 9,
    Premier = 10,
    Dusk = 11,
    Heal = 12,
    Quick = 13,
    Fast = 14,
    Level = 15,
    Lure = 16,
    Heavy = 17,
    Love = 18,
    Friend = 19,
    Moon = 20,
    Sport = 21,
    Dream = 22,
    Beast = 23,
    Safari = 24,
}
