name: Build and deploy
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: windows-latest
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.201
    - name: Execute build
      run: dotnet run --project .\src\ChromaListe.Web\ -- -i .\src\Chromaliste.Web\input\
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.5.6
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        commit_message: Update site with

