name: Build and deploy
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: windows-latest
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Execute build
      run: |
        cd src/ChromaListe.Web
        dotnet run -- -i .\input\ -o ..\..\output\
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
        commit_message: Update site with

